{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3ea397aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "# import json\n",
    "import math\n",
    "import torch\n",
    "from itertools import product\n",
    "from dataclasses import dataclass, field\n",
    "\n",
    "from gamesopt.attacks import Attack\n",
    "from gamesopt.optimizer import Optimizer\n",
    "from gamesopt.aggregator import Aggregator\n",
    "from gamesopt.games import Game, create_matrix, create_bias\n",
    "from gamesopt.train_distributed import train\n",
    "\n",
    "# %matplotlib widget\n",
    "%matplotlib inline\n",
    "%load_ext autoreload\n",
    "%autoreload 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "6874e6d6-dd23-4613-9e3b-1ea2f58263cd",
   "metadata": {},
   "outputs": [],
   "source": [
    "os.environ['MLFLOW_VERBOSE'] = 'True'\n",
    "os.environ['MLFLOW_EXPERIMENT_NAME'] = os.path.basename(os.getcwd())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "ed0a228e-29fc-48c3-8394-fe7ff6f54357",
   "metadata": {},
   "outputs": [],
   "source": [
    "# class Config(BaseConfig):\n",
    "@dataclass\n",
    "class Config():\n",
    "    n_iter: int = 6001\n",
    "\n",
    "    n_peers: int = 100\n",
    "    n_byzan: int = 20\n",
    "\n",
    "    # game: Game = Game.Quadratic\n",
    "    game: Game = field(default_factory=lambda: Game.Quadratic)\n",
    "    num_samples: int = 1000\n",
    "    dim: int = 25\n",
    "    with_bias: bool = True\n",
    "    mu: float = 1e-1\n",
    "    ell: float = 1e3\n",
    "\n",
    "    optimizer: Optimizer = None\n",
    "    batch_size: int = None\n",
    "    lr: float = 1/2/ell/15\n",
    "    alpha: float = None\n",
    "    sigmaC: float = None\n",
    "\n",
    "    attack: Attack = None\n",
    "    n_attacking: int = None\n",
    "    attack_param: float = None\n",
    "\n",
    "    use_bucketing: bool = None\n",
    "    bucketing_s: int = 2\n",
    "\n",
    "    aggregator: Aggregator = None\n",
    "    aggregator_param_a: int = 10  # trimmed_mean_b=10; krum_m=2; ,clipping_n_iter=3 clipping_tau=10\n",
    "    aggregator_param_b: float = 0.1 # rfa_T=10,rfa_nu=0.1    , 0.1)  # rfa_T=10,rfa_nu=0.1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "030aaeb5-5af3-4c52-8af1-985cfec1c345",
   "metadata": {},
   "outputs": [],
   "source": [
    "@dataclass\n",
    "class Data():\n",
    "    def __init__(self, config):\n",
    "        self.matrix = create_matrix(config.dim, config.num_samples,\n",
    "                                    config.mu, config.ell,\n",
    "                                    with_bias=config.with_bias)\n",
    "        self.bias = create_bias(config.dim, config.num_samples,\n",
    "                                with_bias=config.with_bias)\n",
    "        self.true = torch.linalg.solve(self.matrix.mean(dim=0),\n",
    "                                       -self.bias.mean(dim=0))\n",
    "        self.players = self.true + .1/math.sqrt(2 * config.dim)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a578f46b-34c3-421a-b195-ec4c0a8bb00d",
   "metadata": {},
   "outputs": [],
   "source": [
    "base_config = Config()\n",
    "data = Data(base_config)\n",
    "# base_config_items = set(base_config.__dict__.items())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "d0cf2a0c-d94e-41b5-99f7-14aad43cd1f1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trying port 37555\n",
      "Trying port 40809\n",
      "Trying port 10837\n",
      "Trying port 26135\n",
      "2325         \r"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn [9], line 50\u001b[0m\n\u001b[1;32m     48\u001b[0m os\u001b[38;5;241m.\u001b[39menviron[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mMLFLOW_RUN_NAME\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mSEGRA\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m     49\u001b[0m os\u001b[38;5;241m.\u001b[39menviron[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mMLFLOW_RUN_TITLE\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m, bs=\u001b[39m\u001b[38;5;132;01m%i\u001b[39;00m\u001b[38;5;124m'\u001b[39m \u001b[38;5;241m%\u001b[39m (at, bs)\n\u001b[0;32m---> 50\u001b[0m \u001b[43mtrain\u001b[49m\u001b[43m(\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdata\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     52\u001b[0m \u001b[38;5;66;03m# RDEG\u001b[39;00m\n\u001b[1;32m     53\u001b[0m config \u001b[38;5;241m=\u001b[39m Config(attack\u001b[38;5;241m=\u001b[39mat, batch_size\u001b[38;5;241m=\u001b[39mbs)\n",
      "File \u001b[0;32m~/sgda-ra/gamesopt/train_distributed.py:97\u001b[0m, in \u001b[0;36mtrain\u001b[0;34m(config, data)\u001b[0m\n\u001b[1;32m     95\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTrying port \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m%\u001b[39m port)\n\u001b[1;32m     96\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m---> 97\u001b[0m     \u001b[43mmp\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mspawn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m_train\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     98\u001b[0m \u001b[43m             \u001b[49m\u001b[43margs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mport\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdata\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     99\u001b[0m \u001b[43m             \u001b[49m\u001b[38;5;66;43;03m# nprocs=config['n_peers'],\u001b[39;49;00m\n\u001b[1;32m    100\u001b[0m \u001b[43m             \u001b[49m\u001b[38;5;66;43;03m# nprocs=config.n_peers,\u001b[39;49;00m\n\u001b[1;32m    101\u001b[0m \u001b[43m             \u001b[49m\u001b[43mnprocs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mnprocs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    102\u001b[0m \u001b[43m             \u001b[49m\u001b[43mjoin\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n\u001b[1;32m    103\u001b[0m     \u001b[38;5;28;01mbreak\u001b[39;00m\n\u001b[1;32m    104\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m PortNotAvailableError:\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py:230\u001b[0m, in \u001b[0;36mspawn\u001b[0;34m(fn, args, nprocs, join, daemon, start_method)\u001b[0m\n\u001b[1;32m    226\u001b[0m     msg \u001b[38;5;241m=\u001b[39m (\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mThis method only supports start_method=spawn (got: \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m).\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m    227\u001b[0m            \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mTo use a different start_method use:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;130;01m\\t\u001b[39;00m\u001b[38;5;130;01m\\t\u001b[39;00m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m    228\u001b[0m            \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m torch.multiprocessing.start_processes(...)\u001b[39m\u001b[38;5;124m'\u001b[39m \u001b[38;5;241m%\u001b[39m start_method)\n\u001b[1;32m    229\u001b[0m     warnings\u001b[38;5;241m.\u001b[39mwarn(msg)\n\u001b[0;32m--> 230\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mstart_processes\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfn\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mnprocs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mjoin\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdaemon\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstart_method\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mspawn\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py:188\u001b[0m, in \u001b[0;36mstart_processes\u001b[0;34m(fn, args, nprocs, join, daemon, start_method)\u001b[0m\n\u001b[1;32m    185\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m context\n\u001b[1;32m    187\u001b[0m \u001b[38;5;66;03m# Loop on join until it returns True or raises an exception.\u001b[39;00m\n\u001b[0;32m--> 188\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[43mcontext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mjoin\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m:\n\u001b[1;32m    189\u001b[0m     \u001b[38;5;28;01mpass\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py:99\u001b[0m, in \u001b[0;36mProcessContext.join\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m     96\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[1;32m     98\u001b[0m \u001b[38;5;66;03m# Wait for any process to fail or all of them to succeed.\u001b[39;00m\n\u001b[0;32m---> 99\u001b[0m ready \u001b[38;5;241m=\u001b[39m \u001b[43mmultiprocessing\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnection\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    100\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msentinels\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mkeys\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    101\u001b[0m \u001b[43m    \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    102\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    104\u001b[0m error_index \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    105\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m sentinel \u001b[38;5;129;01min\u001b[39;00m ready:\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/multiprocessing/connection.py:936\u001b[0m, in \u001b[0;36mwait\u001b[0;34m(object_list, timeout)\u001b[0m\n\u001b[1;32m    933\u001b[0m     deadline \u001b[38;5;241m=\u001b[39m time\u001b[38;5;241m.\u001b[39mmonotonic() \u001b[38;5;241m+\u001b[39m timeout\n\u001b[1;32m    935\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[0;32m--> 936\u001b[0m     ready \u001b[38;5;241m=\u001b[39m \u001b[43mselector\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mselect\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    937\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m ready:\n\u001b[1;32m    938\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m [key\u001b[38;5;241m.\u001b[39mfileobj \u001b[38;5;28;01mfor\u001b[39;00m (key, events) \u001b[38;5;129;01min\u001b[39;00m ready]\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.9/selectors.py:416\u001b[0m, in \u001b[0;36m_PollLikeSelector.select\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    414\u001b[0m ready \u001b[38;5;241m=\u001b[39m []\n\u001b[1;32m    415\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 416\u001b[0m     fd_event_list \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_selector\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpoll\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    417\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mInterruptedError\u001b[39;00m:\n\u001b[1;32m    418\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m ready\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Process SpawnProcess-402:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:35724\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-403:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:1728\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-405:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:54978\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-409:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:399\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-417:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:30367\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-433:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:11699\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-404:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:2466\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-406:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:9088\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-407:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:50590\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-410:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:18336\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-411:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:47323\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-413:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:34712\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-418:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:15237\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-419:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:8610\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-421:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:34200\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-434:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:6055\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-425:\n",
      "Process SpawnProcess-465:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:23969\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:45483\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-435:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:19859\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-437:\n",
      "Traceback (most recent call last):\n",
      "Process SpawnProcess-408:\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:60032\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:36231\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-412:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:3492\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-415:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:10647\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-414:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:41622\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-420:\n",
      "Process SpawnProcess-441:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "Traceback (most recent call last):\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:35044\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:26335\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-423:\n",
      "Process SpawnProcess-422:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:32652\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:35010\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-426:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:57750\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-449:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:11683\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-427:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:54707\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-436:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:32157\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-466:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:12716\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-439:\n",
      "Process SpawnProcess-438:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:14513\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:6545\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-467:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:10675\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-429:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:25499\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-442:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:2981\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-469:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:36002\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-443:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:6534\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-416:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:20886\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-473:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:21677\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-424:\n",
      "Process SpawnProcess-445:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:8864\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:2204\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "KeyboardInterrupt\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-450:\n",
      "Process SpawnProcess-430:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:21633\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:20909\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-451:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:31622\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-440:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:17543\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-481:\n",
      "Process SpawnProcess-468:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:21427\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:63372\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-453:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:3970\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-446:\n",
      "Process SpawnProcess-471:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:53662\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:30628\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-470:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:22920\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-428:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:54421\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-457:\n",
      "Process SpawnProcess-474:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:25014\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:14752\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-475:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:6548\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-452:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:2753\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-444:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:6044\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-477:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:19354\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-482:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:56972\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-483:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:12525\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-472:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:39638\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-497:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:58034\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-478:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:26336\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-485:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:60561\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-489:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:60836\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-484:\n",
      "Process SpawnProcess-476:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:12199\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:33427\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-454:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:42404\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-459:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:7075\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-498:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:23961\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-499:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:4525\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-455:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:11158\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-458:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:16774\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-431:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:51104\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-447:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:18868\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-486:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:62684\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-491:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:12447\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-487:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:60651\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-490:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:7377\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-500:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:48017\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-479:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:28376\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-460:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:12674\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-432:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:57269\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-448:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:925\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-461:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:14744\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-492:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:10117\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-480:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:42649\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-493:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:16811\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-456:\n",
      "Process SpawnProcess-462:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:62876\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:42730\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-488:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:18846\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-494:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:134\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-464:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:14741\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-463:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:59033\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-496:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.0.1]:17112\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n",
      "Process SpawnProcess-495:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/train_distributed.py\", line 72, in _train\n",
      "    optimizer.step()\n",
      "  File \"/home/nazya/sgda-ra/gamesopt/optimizer/distributed.py\", line 136, in step\n",
      "    dist.broadcast(self.game.players, src=self.game.master_node)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py\", line 1084, in broadcast\n",
      "    work.wait()\n",
      "RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:1440\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 315, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/nazya/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py\", line 59, in _wrap\n",
      "    fn(i, *args)\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "for at, bs in product([Attack.BF],\n",
    "                          # [1e1, 1e2, 1e3, 1e4],\n",
    "                          [1, 10, 100]):\n",
    "\n",
    "    # SGDA\n",
    "    config = Config(attack=at, batch_size=bs)\n",
    "    config.optimizer = Optimizer.SGDA\n",
    "    config.aggregator = Aggregator.Mean\n",
    "    config.n_attacking = config.n_byzan\n",
    "    # config_items = set(config.__dict__.items())\n",
    "    os.environ['MLFLOW_RUN_TAG'] = 'RA'\n",
    "    os.environ['MLFLOW_RUN_NAME'] = 'SGDA'\n",
    "    os.environ['MLFLOW_RUN_TITLE'] = '%s, bs=%i' % (at, bs)\n",
    "    # json.dumps(dict(sorted(config_items - base_config_items)))\n",
    "    train(config, data)\n",
    "\n",
    "    # SGDARA\n",
    "    config = Config(attack=at, batch_size=bs)\n",
    "    config.optimizer = Optimizer.SGDARA\n",
    "    config.aggregator = Aggregator.RFA\n",
    "    config.use_bucketing = True\n",
    "    config.n_attacking = config.n_byzan\n",
    "    os.environ['MLFLOW_RUN_TAG'] = 'RA'\n",
    "    os.environ['MLFLOW_RUN_NAME'] = 'SGDARA'\n",
    "    os.environ['MLFLOW_RUN_TITLE'] = '%s, bs=%i' % (at, bs)\n",
    "    train(config, data)\n",
    "\n",
    "    # MSGDARA\n",
    "    config = Config(attack=at, batch_size=bs)\n",
    "    config.optimizer = Optimizer.MSGDARA\n",
    "    config.alpha = 0.1\n",
    "    config.aggregator = Aggregator.RFA\n",
    "    config.use_bucketing = True\n",
    "    config.n_attacking = config.n_byzan\n",
    "    os.environ['MLFLOW_RUN_TAG'] = 'RA M'\n",
    "    os.environ['MLFLOW_RUN_NAME'] = 'MSGDARA'\n",
    "    os.environ['MLFLOW_RUN_TITLE'] = '%s, bs=%i' % (at, bs)\n",
    "    train(config, data)\n",
    "\n",
    "    # SEGRA\n",
    "    config = Config(attack=at, batch_size=bs)\n",
    "    config.n_iter = int(config.n_iter / 2) + 1\n",
    "    config.optimizer = Optimizer.SEGRA\n",
    "    config.aggregator = Aggregator.RFA\n",
    "    config.use_bucketing = True\n",
    "    config.n_attacking = config.n_byzan\n",
    "    os.environ['MLFLOW_RUN_TAG'] = 'RA'\n",
    "    os.environ['MLFLOW_RUN_NAME'] = 'SEGRA'\n",
    "    os.environ['MLFLOW_RUN_TITLE'] = '%s, bs=%i' % (at, bs)\n",
    "    train(config, data)\n",
    "\n",
    "    # RDEG\n",
    "    config = Config(attack=at, batch_size=bs)\n",
    "    config.n_iter = int(config.n_iter / 2) + 1\n",
    "    config.optimizer = Optimizer.RDEG\n",
    "    config.aggregator = Aggregator.UnivariateTM\n",
    "    config.n_attacking = config.n_byzan\n",
    "    os.environ['MLFLOW_RUN_TAG'] = 'RA'\n",
    "    os.environ['MLFLOW_RUN_NAME'] = 'RDEG'\n",
    "    os.environ['MLFLOW_RUN_TITLE'] = '%s, bs=%i' % (at, bs)\n",
    "    train(config, data)\n",
    "\n",
    "    # SGDACC\n",
    "    config = Config(attack=at, batch_size=bs)\n",
    "    config.n_iter = config.n_iter * 2 - 1\n",
    "    config.optimizer = Optimizer.SGDACC\n",
    "    config.aggregator = Aggregator.Mean\n",
    "    config.sigmaC = 100.\n",
    "    config.n_attacking = 1\n",
    "    os.environ['MLFLOW_RUN_TAG'] = 'CC'\n",
    "    os.environ['MLFLOW_RUN_NAME'] = 'SGDACC'\n",
    "    os.environ['MLFLOW_RUN_TITLE'] = '%s, bs=%i' % (at, bs)\n",
    "    train(config, data)\n",
    "\n",
    "    # SEGCC\n",
    "    config = Config(attack=at, batch_size=bs)\n",
    "    config.n_iter = config.n_iter + 1\n",
    "    config.optimizer = Optimizer.SEGCC\n",
    "    config.aggregator = Aggregator.Mean\n",
    "    config.sigmaC = 100.\n",
    "    config.n_attacking = 1\n",
    "    os.environ['MLFLOW_RUN_TAG'] = 'CC'\n",
    "    os.environ['MLFLOW_RUN_NAME'] = 'SEGCC'\n",
    "    os.environ['MLFLOW_RUN_TITLE'] = '%s, bs=%i' % (at, bs)\n",
    "    train(config, data)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ffbd2ee-7523-41b6-b398-4edba7d2b897",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.15"
  },
  "vscode": {
   "interpreter": {
    "hash": "18f7a5ae47153a9b42c5447ccb1bbe68959e117ab7750209e163c7c253c9e013"
   }
  },
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {},
    "version_major": 2,
    "version_minor": 0
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
